SportStore.Stores/Components/CartSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportStore.Stores.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportStore.Stores.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart { get; set; }
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

SportStore.Stores/Components/NavigationMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using SportStore.Stores.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SportStore.Stores.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {
        private IStoreRepository repository;
        public NavigationMenuViewComponent(IStoreRepository repo)
        {
            repository = repo;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["category"];
            return View(repository.Products
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

SportStore.Stores/Views/Shared/ProductSummary.cshtml
@model Product
@{
}
<div class="card m-1 p-1">
    <div class="bg-success p-1">
        <h4>
            @Model.Name
            <span class="badge rounded-pill bg-primary" style="float:right">
                <small>@Model.Price.ToString("C")</small>
            </span> 
        </h4>
    </div>
    <form id="@Model.ProductId" asp-page="/cart" method="post">
        <input type="hidden" asp-for="ProductId" />
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
            @Model.Description
            <button type="submit" class="btn btn-success pull-right" style="float:right">
                Add To Cart
            </button>
        </span>
    </form>
</div>

SportStore.Stores/Views/Shared/_Layout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link href="~/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <title>Sport Store</title>
</head>
    <body>
        <div class="bg-dark text-white p-2">
            <div class="container-fluid">
                <div class="col navbar-brand ml-2">Sports Store</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
            
        </div>
        <div class="row m-1 p-1" >
            <div class="col-3" id="categories">
                <vc:navigation-menu />
            </div>
            <div class="col-9">
                @RenderBody()
            </div>
        </div>
    </body>
</html>